apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- serviceaccount.yaml
- role.yaml
- rolebinding.yaml
- deployment.yaml
- service.yaml
- configmap.yaml
- secret.yaml
- networkpolicy.yaml

labels:
- includeSelectors: true
  pairs:
    app: pixels
    environment: base
