apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- serviceaccount.yaml
- role.yaml
- rolebinding.yaml
- deployment.yaml
- service.yaml
- configmap.yaml
- secret.yaml
- networkpolicy.yaml
- postgres-configmap.yaml
- postgres-secret.yaml
- postgres-pvc.yaml
- postgres-deployment.yaml
- postgres-service.yaml
- migration-job.yaml

configurations:
- kustomizeconfig.yaml