apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pixels-rolebinding
subjects:
  - kind: ServiceAccount
    name: pixels-sa
roleRef:
  kind: Role
  name: pixels-role
  apiGroup: rbac.authorization.k8s.io
