name: Self-Hosted Runner Test

on:
  pull_request:
    branches: [ main ]

jobs:
  smoke:
    runs-on: [self-hosted, k3s, pixels]
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3]  # run 3 jobs in parallel to test scaling
    steps:
      - name: Show runner context
        run: |
          echo "Runner name: $RUNNER_NAME"
          echo "Runner os: $RUNNER_OS"
          echo "Job shard: ${{ matrix.shard }}"
          echo "Labels: $RUNNER_LABELS"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Basic commands
        run: |
          uname -a
          which docker || true
          which kubectl || true

      - name: Simulate work
        run: |
          echo "Starting shard ${{ matrix.shard }}..."
          sleep $(( (RANDOM % 10) + 5 ))
          echo "Done shard ${{ matrix.shard }}"
