apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: pixels-staging
patches:
- path: configmap.yaml
- path: postgres-configmap-patch.yaml
images:
  - name: pixels
    newName: ghcr.io/pokemonpower92/pixels/api
  - name: migrate
    newName: ghcr.io/pokemonpower92/pixels/migrate
labels:
- includeSelectors: true
  pairs:
    environment: staging
